FROM public.ecr.aws/lambda/python:3.9

# Set environment variables for Python
ENV PYTHONUNBUFFERED=true \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    HOME=/tmp \
    XDG_CACHE_HOME=/tmp

# Copy requirements and install Python packages
COPY requirements.txt /var/task/requirements.txt
RUN pip install -r /var/task/requirements.txt --target /var/task

# Copy the Lambda function code
COPY lambda_function.py /var/task

# Set the CMD to your handler
CMD ["lambda_function.lambda_handler"]

