import { mapFormToDocgenAnswers } from "../src/lib/agreement-mapper";
import { generateDocument } from "../src/lib/agreement-docgen";
import { inflateRawSync } from "node:zlib";
const N=["Roberto Mendez","Ana Garcia"];
const oa=(n:number)=>Array.from({length:n},(_,i)=>({fullName:N[i],firstName:N[i].split(" ")[0],lastName:N[i].split(" ").slice(1).join(" "),ownership:i===n-1?100-Math.floor(100/n)*(n-1):Math.floor(100/n)}));
function llcFD(n:number){const a:any={wants:"Yes",majorityThreshold:50.01,supermajorityThreshold:75,distributionFrequency:"Trimestral",llc_companySaleDecision:"Mayoría",llc_bankSigners:"Dos firmantes",llc_majorDecisions:"Mayoría",llc_majorSpendingThreshold:"15000",llc_officerRemovalVoting:"Mayoría",llc_nonCompete:"No",llc_nonSolicitation:"No",llc_confidentiality:"No",llc_nonDisparagement:"Yes",llc_taxPartner:N[0],llc_minTaxDistribution:30,llc_rofr:"No",llc_rofrOfferPeriod:180,llc_tagDragRights:"No",llc_incapacityHeirsPolicy:"Yes",llc_dissolutionDecision:"Mayoría",llc_newMembersAdmission:"Mayoría",llc_newPartnersAdmission:"Mayoría",llc_managingMembers:"Yes",llc_additionalContributions:"Sí, Pro-Rata",llc_additionalContributionsDecision:"Mayoría",llc_memberLoans:"Yes",llc_memberLoansVoting:"Mayoría"};for(let i=0;i<n;i++)a[`llc_capitalContributions_${i}`]="50000";return{company:{entityType:"LLC",companyName:"SIG LLC",companyNameBase:"SIG LLC",entitySuffix:"LLC",hasUsAddress:"No",hasUsPhone:"No",state:"Florida"},ownersCount:n,owners:Object.fromEntries(oa(n).map((o,i)=>[String(i),{...o,ownershipPercentage:o.ownership,ownerType:"persona",isUsCitizen:"No"}])),admin:{managersAllOwners:"Yes"},agreement:a};}
function corpFD(n:number){const a:any={wants:"Yes",majorityThreshold:50.01,supermajorityThreshold:75,distributionFrequency:"Trimestral",corp_saleDecisionThreshold:"Mayoría",corp_bankSigners:"Dos firmantes",corp_majorDecisionThreshold:"Mayoría",corp_majorSpendingThreshold:"7500",corp_officerRemovalVoting:"Mayoría",corp_nonCompete:"No",corp_nonSolicitation:"No",corp_confidentiality:"No",corp_taxOwner:N[0],corp_rofr:"No",corp_rofrOfferPeriod:90,corp_incapacityHeirsPolicy:"Yes",corp_divorceBuyoutPolicy:"Yes",corp_tagDragRights:"No",corp_newShareholdersAdmission:"Mayoría",corp_moreCapitalProcess:"Sí, Pro-Rata",corp_moreCapitalDecision:"Mayoría",corp_shareholderLoans:"Yes",corp_shareholderLoansVoting:"Mayoría"};for(let i=0;i<n;i++)a[`corp_capitalPerOwner_${i}`]="50000";const admin:any={directorsAllOwners:"Yes",officersAllOwners:"Yes"};["President","Treasurer"].slice(0,n).forEach((r,i)=>admin[`shareholderOfficer${i+1}Role`]=r);return{company:{entityType:"C-Corp",companyName:"SIG Corp",companyNameBase:"SIG Corp",entitySuffix:"Inc.",hasUsAddress:"No",hasUsPhone:"No",state:"Florida",corpType:"Corp"},ownersCount:n,owners:Object.fromEntries(oa(n).map((o,i)=>[String(i),{...o,ownershipPercentage:o.ownership,ownerType:"persona",isUsCitizen:"No"}])),admin,agreement:a};}
function dx(buf:Buffer){const eocd=buf.lastIndexOf(Buffer.from([0x50,0x4b,0x05,0x06]));let o=buf.readUInt32LE(eocd+16);while(buf.readUInt32LE(o)===0x02014b50){const cl=buf.readUInt16LE(o+28),el=buf.readUInt16LE(o+30),fl=buf.readUInt16LE(o+32),lho=buf.readUInt32LE(o+42);const nm=buf.toString("utf8",o+46,o+46+cl);const ds=lho+30+buf.readUInt16LE(lho+26)+buf.readUInt16LE(lho+28);const csz=buf.readUInt32LE(o+20),cp=buf.readUInt16LE(o+10);if(nm==="word/document.xml")return(cp===8?inflateRawSync(buf.subarray(ds,ds+csz)):buf.subarray(ds,ds+csz)).toString("utf8");o+=46+cl+el+fl;}return"";}
function report(label:string,xml:string){const mi=xml.search(/SIGNATURE PAGE/);const wi=xml.search(/IN WITNESS WHEREOF/);const gap=xml.substring(mi,wi);const br=/<w:br\b[^>]*w:type="page"/.test(gap);
  // witness paragraph
  const wp=(xml.substring(wi-600,wi+400).match(/<w:p\b[^>]*>[\s\S]*?IN WITNESS WHEREOF[\s\S]*?<\/w:p>/)||[""])[0];
  const pbb=/<w:pageBreakBefore\b(?![^>]*w:val="0")/.test(wp);
  console.log(`${label}: marker present=${mi>=0} | gap has <w:br page>=${br} | witness pageBreakBefore=${pbb} | breaks-total=${(br?1:0)+(pbb?1:0)}`);}
(async()=>{
  report("LLC 1o",dx((await generateDocument(await mapFormToDocgenAnswers(llcFD(1) as any))).buffer));
  report("LLC 2o",dx((await generateDocument(await mapFormToDocgenAnswers(llcFD(2) as any))).buffer));
  report("Corp 1o",dx((await generateDocument(await mapFormToDocgenAnswers(corpFD(1) as any))).buffer));
  report("Corp 2o",dx((await generateDocument(await mapFormToDocgenAnswers(corpFD(2) as any))).buffer));
})();
