import zlib from "node:zlib";
import { mapFormToDocgenAnswers } from "../src/lib/agreement-mapper";
import { generateDocument } from "../src/lib/agreement-docgen";
const NAMES=["Roberto Mendez","Ana Garcia","Carlos Lopez"];
const OFF=["President","Vice-President","Secretary"];
const U="Decisión Unánime";
function corpAg(n:number){const a:any={wants:"Yes",majorityThreshold:50.01,supermajorityThreshold:75,distributionFrequency:"Trimestral"};Object.assign(a,{corp_saleDecisionThreshold:U,corp_bankSigners:"Dos firmantes",corp_majorDecisionThreshold:U,corp_majorSpendingThreshold:"7500",corp_officerRemovalVoting:U,corp_nonCompete:"No",corp_nonSolicitation:"No",corp_confidentiality:"No",corp_taxOwner:NAMES[0],corp_rofr:"Yes",corp_rofrOfferPeriod:90,corp_incapacityHeirsPolicy:"Yes",corp_divorceBuyoutPolicy:"Yes",corp_tagDragRights:"No",corp_newShareholdersAdmission:U,corp_moreCapitalProcess:"Sí, Pro-Rata",corp_moreCapitalDecision:U,corp_shareholderLoans:"Yes",corp_shareholderLoansVoting:U});for(let i=0;i<n;i++)a[`corp_capitalPerOwner_${i}`]="50000";return a;}
function fd(n:number){const owners=Array.from({length:n},(_,i)=>({fullName:NAMES[i],firstName:NAMES[i].split(" ")[0],lastName:NAMES[i].split(" ").slice(1).join(" "),ownership:Math.floor(100/n)+(i===n-1?100-Math.floor(100/n)*n:0)}));const admin:any={directorsAllOwners:"Yes",officersAllOwners:"Yes"};OFF.slice(0,n).forEach((r,i)=>admin[`shareholderOfficer${i+1}Role`]=r);return{company:{entityType:"C-Corp",companyName:"RMV Corp",companyNameBase:"RMV Corp",entitySuffix:"Inc.",hasUsAddress:"No",hasUsPhone:"No",state:"Florida",corpType:"Corp"},ownersCount:n,owners:Object.fromEntries(owners.map((o,i)=>[String(i),{...o,ownershipPercentage:o.ownership,ownerType:"persona",isUsCitizen:"No"}])),admin,agreement:corpAg(n)};}
function docXml(buf:Buffer){const eocd=buf.lastIndexOf(Buffer.from([0x50,0x4b,0x05,0x06]));let o=buf.readUInt32LE(eocd+16);while(buf.readUInt32LE(o)===0x02014b50){const cl=buf.readUInt16LE(o+28),el=buf.readUInt16LE(o+30),fl=buf.readUInt16LE(o+32),lho=buf.readUInt32LE(o+42);const nm=buf.toString("utf8",o+46,o+46+cl);const ds=lho+30+buf.readUInt16LE(lho+26)+buf.readUInt16LE(lho+28);const csz=buf.readUInt32LE(o+20),cp=buf.readUInt16LE(o+10);if(nm==="word/document.xml")return(cp===8?zlib.inflateRawSync(buf.subarray(ds,ds+csz)):buf.subarray(ds,ds+csz)).toString("utf8");o+=46+cl+el+fl;}return"";}
(async()=>{const xml=docXml((await generateDocument(await mapFormToDocgenAnswers(fd(3) as any))).buffer);const j=[...xml.matchAll(/<w:t[^>]*>([^<]*)<\/w:t>/g)].map(m=>m[1]).join("").replace(/\s+/g," ");const i=j.indexOf("12.1 Removal");console.log("§12.1: "+JSON.stringify(j.slice(i,i+260)));console.log("has doubled 'consent of Unanimous consent of': "+/consent of Unanimous consent of/.test(j));})();
