import { mapFormToDocgenAnswers } from "../src/lib/agreement-mapper";
import { generateDocument } from "../src/lib/agreement-docgen";
import { inflateRawSync } from "node:zlib";
const a:any={wants:"Yes",majorityThreshold:50.01,supermajorityThreshold:75,distributionFrequency:"Trimestral",llc_companySaleDecision:"Mayoría",llc_bankSigners:"Dos firmantes",llc_majorDecisions:"Mayoría",llc_majorSpendingThreshold:"15000",llc_officerRemovalVoting:"Mayoría",llc_nonCompete:"No",llc_nonSolicitation:"No",llc_confidentiality:"No",llc_nonDisparagement:"Yes",llc_taxPartner:"Roberto Mendez",llc_minTaxDistribution:30,llc_rofr:"No",llc_rofrOfferPeriod:180,llc_tagDragRights:"No",llc_incapacityHeirsPolicy:"Yes",llc_dissolutionDecision:"Mayoría",llc_newMembersAdmission:"Mayoría",llc_newPartnersAdmission:"Mayoría",llc_managingMembers:"Yes",llc_additionalContributions:"Sí, Pro-Rata",llc_additionalContributionsDecision:"Mayoría",llc_memberLoans:"Yes",llc_memberLoansVoting:"Mayoría",llc_capitalContributions_0:"50000"};
const fd={company:{entityType:"LLC",companyName:"SIG LLC",companyNameBase:"SIG LLC",entitySuffix:"LLC",hasUsAddress:"No",hasUsPhone:"No",state:"Florida"},ownersCount:1,owners:{"0":{fullName:"Roberto Mendez",firstName:"Roberto",lastName:"Mendez",ownershipPercentage:100,ownerType:"persona",isUsCitizen:"No"}},admin:{managersAllOwners:"Yes"},agreement:a};
function dx(buf:Buffer){const eocd=buf.lastIndexOf(Buffer.from([0x50,0x4b,0x05,0x06]));let o=buf.readUInt32LE(eocd+16);while(buf.readUInt32LE(o)===0x02014b50){const cl=buf.readUInt16LE(o+28),el=buf.readUInt16LE(o+30),fl=buf.readUInt16LE(o+32),lho=buf.readUInt32LE(o+42);const nm=buf.toString("utf8",o+46,o+46+cl);const ds=lho+30+buf.readUInt16LE(lho+26)+buf.readUInt16LE(lho+28);const csz=buf.readUInt32LE(o+20),cp=buf.readUInt16LE(o+10);if(nm==="word/document.xml")return(cp===8?inflateRawSync(buf.subarray(ds,ds+csz)):buf.subarray(ds,ds+csz)).toString("utf8");o+=46+cl+el+fl;}return"";}
(async()=>{const xml=dx((await generateDocument(await mapFormToDocgenAnswers(fd as any))).buffer);
  // exact marker paragraph text
  for(const p of xml.match(/<w:p\b[^>]*>[\s\S]*?<\/w:p>/g)||[]){const t=(p.match(/<w:t[^>]*>[^<]*<\/w:t>/g)||[]).map(x=>x.replace(/<[^>]+>/g,"")).join("");if(/SIGNATURE PAGE/.test(t))console.log("MARKER txt="+JSON.stringify(t)+" (trim="+JSON.stringify(t.trim())+")");
    if(t.trim().startsWith("IN WITNESS WHEREOF")){console.log("WITNESS pPr="+ (p.match(/<w:pPr>[\s\S]*?<\/w:pPr>/)||["(none)"])[0].slice(0,160));console.log("WITNESS has pageBreakBefore="+/pageBreakBefore/.test(p));}}
})();
