import { writeFileSync } from "node:fs";
import { mapFormToDocgenAnswers } from "../src/lib/agreement-mapper";
import { generateDocument } from "../src/lib/agreement-docgen";
const NAMES=["Roberto Mendez","Ana Garcia","Carlos Lopez","Maria Torres","Pedro Ramirez","Sofia Flores"];
const OFF=["President","Vice-President","Secretary","Treasurer","Assistant Vice-President","Assistant Secretary"];
const ownerArray=(n:number)=>{const pct=Math.floor(100/n);return Array.from({length:n},(_,i)=>({fullName:NAMES[i],firstName:NAMES[i].split(" ")[0],lastName:NAMES[i].split(" ").slice(1).join(" "),ownership:i===n-1?100-pct*(n-1):pct}));};
function ag(n:number){const a:any={wants:"Yes",majorityThreshold:50.01,supermajorityThreshold:75,distributionFrequency:"Trimestral"};Object.assign(a,{corp_saleDecisionThreshold:"Supermayoría",corp_bankSigners:"Dos firmantes",corp_majorDecisionThreshold:"Supermayoría",corp_majorSpendingThreshold:"7500",corp_officerRemovalVoting:"Supermayoría",corp_nonCompete:"Yes",corp_nonSolicitation:"Yes",corp_confidentiality:"Yes",corp_taxOwner:NAMES[0],corp_rofr:"Yes",corp_rofrOfferPeriod:90,corp_incapacityHeirsPolicy:"Yes",corp_divorceBuyoutPolicy:"Yes",corp_tagDragRights:"Yes",corp_newShareholdersAdmission:"Supermayoría",corp_moreCapitalProcess:"Sí, Pro-Rata",corp_moreCapitalDecision:"Supermayoría",corp_shareholderLoans:"Yes",corp_shareholderLoansVoting:"Supermayoría"});for(let i=0;i<n;i++)a[`corp_capitalPerOwner_${i}`]="50000";return a;}
function fd(n:number){const o=ownerArray(n);const admin:any={directorsAllOwners:"Yes",officersAllOwners:"Yes"};OFF.slice(0,n).forEach((r,i)=>admin[`shareholderOfficer${i+1}Role`]=r);return{company:{entityType:"C-Corp",companyName:"AUDIT Corp",companyNameBase:"AUDIT Corp",entitySuffix:"Inc.",hasUsAddress:"No",hasUsPhone:"No",state:"Florida",corpType:"Corp"},ownersCount:n,owners:Object.fromEntries(o.map((x,i)=>[String(i),{...x,ownershipPercentage:x.ownership,ownerType:"persona",isUsCitizen:"No"}])),admin,agreement:ag(n)};}
(async()=>{for(const n of [3,6]){const buf=(await generateDocument(await mapFormToDocgenAnswers(fd(n) as any))).buffer;writeFileSync(`/tmp/audit_corp_${n}o.docx`,buf);console.log(`wrote /tmp/audit_corp_${n}o.docx (${buf.length}b)`);}})();
