import { writeFileSync } from "node:fs";
import { mapFormToDocgenAnswers } from "../src/lib/agreement-mapper";
import { generateDocument } from "../src/lib/agreement-docgen";
const N=["Roberto Mendez","Ana Garcia"];
const oa=(n:number)=>Array.from({length:n},(_,i)=>({fullName:N[i],firstName:N[i].split(" ")[0],lastName:N[i].split(" ").slice(1).join(" "),ownership:i===n-1?100-Math.floor(100/n)*(n-1):Math.floor(100/n)}));
function llcFD(n:number){const a:any={wants:"Yes",majorityThreshold:50.01,supermajorityThreshold:75,distributionFrequency:"Trimestral",llc_companySaleDecision:"Mayoría",llc_bankSigners:"Dos firmantes",llc_majorDecisions:"Mayoría",llc_majorSpendingThreshold:"15000",llc_officerRemovalVoting:"Mayoría",llc_nonCompete:"No",llc_nonSolicitation:"No",llc_confidentiality:"No",llc_nonDisparagement:"Yes",llc_taxPartner:N[0],llc_minTaxDistribution:30,llc_rofr:"No",llc_rofrOfferPeriod:180,llc_tagDragRights:"No",llc_incapacityHeirsPolicy:"Yes",llc_dissolutionDecision:"Mayoría",llc_newMembersAdmission:"Mayoría",llc_newPartnersAdmission:"Mayoría",llc_managingMembers:"Yes",llc_additionalContributions:"Sí, Pro-Rata",llc_additionalContributionsDecision:"Mayoría",llc_memberLoans:"Yes",llc_memberLoansVoting:"Mayoría"};for(let i=0;i<n;i++)a[`llc_capitalContributions_${i}`]="50000";return{company:{entityType:"LLC",companyName:"SIGTEST LLC",companyNameBase:"SIGTEST LLC",entitySuffix:"LLC",hasUsAddress:"No",hasUsPhone:"No",state:"Florida"},ownersCount:n,owners:Object.fromEntries(oa(n).map((o,i)=>[String(i),{...o,ownershipPercentage:o.ownership,ownerType:"persona",isUsCitizen:"No"}])),admin:{managersAllOwners:"Yes"},agreement:a};}
function corpFD(n:number){const a:any={wants:"Yes",majorityThreshold:50.01,supermajorityThreshold:75,distributionFrequency:"Trimestral",corp_saleDecisionThreshold:"Mayoría",corp_bankSigners:"Dos firmantes",corp_majorDecisionThreshold:"Mayoría",corp_majorSpendingThreshold:"7500",corp_officerRemovalVoting:"Mayoría",corp_nonCompete:"No",corp_nonSolicitation:"No",corp_confidentiality:"No",corp_taxOwner:N[0],corp_rofr:"No",corp_rofrOfferPeriod:90,corp_incapacityHeirsPolicy:"Yes",corp_divorceBuyoutPolicy:"Yes",corp_tagDragRights:"No",corp_newShareholdersAdmission:"Mayoría",corp_moreCapitalProcess:"Sí, Pro-Rata",corp_moreCapitalDecision:"Mayoría",corp_shareholderLoans:"Yes",corp_shareholderLoansVoting:"Mayoría"};for(let i=0;i<n;i++)a[`corp_capitalPerOwner_${i}`]="50000";const admin:any={directorsAllOwners:"Yes",officersAllOwners:"Yes"};["President","Treasurer"].slice(0,n).forEach((r,i)=>admin[`shareholderOfficer${i+1}Role`]=r);return{company:{entityType:"C-Corp",companyName:"SIGTEST Corp",companyNameBase:"SIGTEST Corp",entitySuffix:"Inc.",hasUsAddress:"No",hasUsPhone:"No",state:"Florida",corpType:"Corp"},ownersCount:n,owners:Object.fromEntries(oa(n).map((o,i)=>[String(i),{...o,ownershipPercentage:o.ownership,ownerType:"persona",isUsCitizen:"No"}])),admin,agreement:a};}
(async()=>{const D="Downloads/e2e-uat-edge-variants/_sigtest/";require("node:fs").mkdirSync(D,{recursive:true});
  writeFileSync(D+"llc2.docx",(await generateDocument(await mapFormToDocgenAnswers(llcFD(2) as any))).buffer);
  writeFileSync(D+"corp2.docx",(await generateDocument(await mapFormToDocgenAnswers(corpFD(2) as any))).buffer);
  console.log("saved llc2.docx + corp2.docx");})();
